name       : autojump
version    : 22.5.1
release    : 1
source     :
    - https://github.com/wting/autojump/archive/release-v22.5.1.tar.gz : 765fabda130eb4df70d1c1e5bc172e1d18f8ec22c6b89ff98f1674335292e99f
license    : GPL-3.0
component  : system.utils
summary    : A faster way to navigate your filesystem
description: |
    A cd command that learns - easily navigate directories from the command line
setup      : |
    sed -i 's:.autojump/share/autojump/:.autojump/:g' bin/autojump.sh
    sed -i 's:/usr/local/:/usr/:g' bin/autojump.sh
    sed -i '213d' install.py
install    : |
    python install.py \
        --destdir "$installdir" \
        --prefix "usr" \
        --zshshare "usr/share/zsh/site-functions/"
